name: Security Vulnerability
description: Report a security vulnerability
title: "[Security]: "
labels: ["security", "high-priority"]
body:
  - type: markdown
    attributes:
      value: |
        # Security Vulnerability Report
        
        **⚠️ IMPORTANT: For security vulnerabilities, please DO NOT file a public issue.**
        
        Instead, send your report to our security team at: security@motionmath.ai
        
        If you must use GitHub, please mark this issue as confidential and provide minimal details.

  - type: textarea
    id: vulnerability-type
    attributes:
      label: Vulnerability Type
      description: What type of vulnerability is this?
      placeholder: e.g., XSS, SQL Injection, CSRF, Authentication Bypass, etc.
    validations:
      required: true

  - type: textarea
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this vulnerability?
      placeholder: Critical / High / Medium / Low
    validations:
      required: true

  - type: textarea
    id: affected-versions
    attributes:
      label: Affected Versions
      description: Which versions are affected?
      placeholder: e.g., v1.0.0 - v1.2.3
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: What is the potential impact of this vulnerability?
      placeholder: Describe the potential damage or risk...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Next Steps
        
        Our security team will:
        1. Acknowledge receipt within 24 hours
        2. Investigate the report within 7 days
        3. Provide a timeline for resolution
        4. Coordinate disclosure if needed
        
        Thank you for helping keep MotionMath AI secure!
